model:
  name: "csar-dualview"
  embedding_dim: 64
  orth_loss_weight: [0.3]
  exclusive_loss_weight: [0.3, 0.5]
  num_interests: [16, 32, 64]
  scale: True
  temperature: [0.05, 0.1, 0.2]
  use_zscore: False
  normalize: False
  emb_dropout: [0.0, 0.1]
  l2_reg_weight: [0.001]

# 학습 설정
train:
  epochs: 500
  batch_size: 512
  lr: 0.001
  l2_regularization: 0.0 # Reduced since we use Activation L2 Reg
  optimizer: "adamw"
  loss_type: "pairwise"
  num_negatives: 60
  negative_sampling_strategy: ["uniform"]
  negative_sampling_alpha: 0.75
  early_stop_patience: 40

# 평가 설정
evaluation:
  batch_size: 512
  validation_method: "full_subset"
  final_method: "full"
  metrics:
    [
      "NDCG",
      "HitRate",
      "Coverage",
      "GiniIndex",
      "LongTailCoverage",
      "Entropy",
      "ILD",
      "GiniIndex_emb",
      "Novelty",
    ]
  top_k: [5, 10, 20, 50]
  main_metric: "NDCG"
  main_metric_k: 10
  long_tail_percent: 0.2

# 실행 환경 설정
device: "auto"
