# ItemKNN 모델 설정
model:
  name: "ItemKNN"
  k: 50 # 사용할 최근접 이웃의 수

evaluation:
  main_metric: "NDCG"
  main_metric_k: 10
  validation_method: "uni99"
  final_method: "full"
  metrics:
    ["HitRate", "NDCG", "Coverage", "GiniIndex", "LongTailCoverage", "Entropy"]
  top_k: [5, 10, 20]

device: "auto"
