# NeuMF 모델 설정
model:
  name: "NeuMF"
  embedding_dim_gmf: 32
  embedding_dim_mlp: 32
  mlp_layers: [[64, 32, 16]]

train:
  epochs: 500
  batch_size: 1024
  lr: 0.001
  l2_regularization: 0.001
  optimizer: "adamw"
  loss_type: "pairwise" # 'pairwise', 'pointwise'
  num_negatives: 1 # For pairwise losses
  negative_sampling_strategy: ["uniform", "popularity"] # 'uniform' or 'popularity'
  negative_sampling_alpha: 0.75
  early_stop_patience: 40

evaluation:
  main_metric: "NDCG"
  main_metric_k: 10
  validation_method: "uni99"
  final_method: "full"
  metrics:
    ["HitRate", "NDCG", "Coverage", "GiniIndex", "LongTailCoverage", "Entropy"]
  top_k: [5, 10, 20]

device: "auto"
