# 데이터셋 설정
dataset_name: "ml-100k"
data_path: "/Users/leejongmin/code/recsys_framework/data/ml100k/u.data"
separator: '\t'
columns: ["user_id", "item_id", "rating", "timestamp"]

# 데이터 전처리 및 분할 설정
rating_threshold: 4 # 이 값 이상의 평점만 상호작용으로 간주
min_user_interactions: 5
min_item_interactions: 5
split_method: "loo" # Leave-One-Out
data_cache_path: "./data_cache/"
