model:
  name: "DICE"
  embedding_dim: 64
  dis_pen: 0.02
  int_weight: 0.1
  pop_weight: 0.1

train:
  batch_size: 256
  epochs: 500
  lr: 0.001
  loss_type: "pairwise"
  optimizer: "adam"
  l2_regularization: 0.0001
  num_negatives: 1
  negative_sampling_strategy: "uniform" # DICE typically benefits from pop sampling awareness
  negative_sampling_alpha: 0.75
  early_stop_patience: 400

evaluation:
  validation_method: "sampled" # 검증 시 평가 방법
  final_method: "full" # 최종 평가 시 평가 방법
  metrics: [
      "NDCG",
      "HitRate",
      "Coverage",
      "GiniIndex",
      "LongTailCoverage",
      "Entropy",
      "ILD",
      "GiniIndex_emb",
      "Novelty",
    ] # 평가할 메트릭 리스트
  top_k: [5, 10, 20, 50] # 평가할 K 값 리스트
  main_metric: "NDCG" # 얼리 스톱핑 및 베스트 모델 저장 기준 메트릭
  main_metric_k: 10 # 얼리 스톱핑 및 베스트 모델 저장 기준 메트릭의 K 값
  long_tail_percent: 0.2 # 롱테일 아이템 정의를 위한 비율 (인기도 하위 N%)

# 실행 환경 설정
device: "auto"
