model:
  name: protomf
  embedding_dim: 64
  num_prototypes: 10 # Number of prototypes
  lambda_orth: 0.1 # Orthogonality regularization weight

train:
  batch_size: 1024
  epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  loss_type: pairwise
  num_negatives: 1
  negative_sampling_strategy: uniform

evaluation:
  validation_method: "uni99" # 검증 시 평가 방법
  final_method: "full" # 최종 평가 시 평가 방법
  metrics: [
      "NDCG",
      "HitRate",
      "Coverage",
      "GiniIndex",
      "LongTailCoverage",
      "Entropy",
      "ILD",
      "GiniIndex_emb",
    ] # 평가할 메트릭 리스트
  top_k: [5, 10, 20] # 평가할 K 값 리스트
  main_metric: "NDCG" # 얼리 스톱핑 및 베스트 모델 저장 기준 메트릭
  main_metric_k: 20 # 얼리 스톱핑 및 베스트 모델 저장 기준 메트릭의 K 값
  long_tail_percent: 0.2 # 롱테일 아이템 정의를 위한 비율 (인기도 하위 N%)

# 실행 환경 설정
device: "auto"
