model:
  name: "protomf-sampled"
  embedding_dim: 64
  num_prototypes: 96 # Number of prototypes
  sim_proto_weight: 0.1
  sim_batch_weight: 0.1
  cosine_type: "shifted"
  mode: "UI"

  # Sampled Softmax parameters
  temperature: 1.0
  use_zscore: False

train:
  batch_size: 512
  epochs: 500
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  loss_type: pairwise
  num_negatives: 60 # Sampled Softmax용 네거티브 수
  negative_sampling_strategy: ["uniform"]
  negative_sampling_alpha: 0.75
  early_stop_patience: 30

evaluation:
  batch_size: 512
  validation_method: "full_subset"
  final_method: "full"
  metrics:
    [
      "NDCG",
      "HitRate",
      "Coverage",
      "GiniIndex",
      "LongTailCoverage",
      "Entropy",
      "ILD",
      "GiniIndex_emb",
      "Novelty",
    ]
  top_k: [5, 10, 20, 50]
  main_metric: "NDCG"
  main_metric_k: 10
  long_tail_percent: 0.2

device: "auto"
